Repository meows/party, pull requests merged in 2023-06, with the labels that each got.

#5 docs: add links to recommended VSCode extensions
  README.md
Labels: documentation

#11 fix: React `ghostText` prop warning
  src/pages/index.tsx
Labels: invalid

#16 feat: add PR template to encourage screenshots
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#17 readme: info on dev server over local network
  README.md
Labels: documentation
